### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by pmuvva** [kenshin03/Home-For-iOS#19]
Hi,

I used below command line to compile the workspace:
xcodebuild -workspace demoApp.xcworkspace -scheme "demoAppCWS" -arch i386  -configuration $(XCODE_CONFIGURATION) -sdk iphonesimulator$(SDK_VER) build RUN_CLANG_STATIC_ANALYZER=YES

I got the the error: 
fatal error: file '/Users/pmuvva/gitrepo/iOS/demoApp/Pods/Target Support Files/Pods/Pods-environment.h' has been modified since the precompiled header
      '/Users/pmuvva/Library/Developer/Xcode/DerivedData/demoApp-aysavilfyulpfuhhvzbiqwwoyzzd/Build/Intermediates/PrecompiledHeaders/Pods-Brightcove-Player-SDK-prefix-cuaepauopatfpfdniaqufyufqtzi/Pods-Brightcove-Player-SDK-prefix.pch.pch'
      was built
note: please rebuild precompiled header
      '/Users/pmuvva/Library/Developer/Xcode/DerivedData/demoApp-aysavilfyulpfuhhvzbiqwwoyzzd/Build/Intermediates/PrecompiledHeaders/Pods-Brightcove-Player-SDK-prefix-cuaepauopatfpfdniaqufyufqtzi/Pods-Brightcove-Player-SDK-prefix.pch.pch'
1 error generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

** BUILD FAILED **

If I replace the architecture from i386 to X86_64 then it doesn't show the error.
I am using Xcode 6.1.1

I referred #2394 still I am not able to resolve......

Any info regarding this issue...

**Comment by kenshin03** [comment]
Hi @pmuvva, I ran a fresh Pod install on the project and manually fixed some MR shorthand issues. 

By the way, your error logs is referring to Brightcove-Player-SDK? You should manually set the Pods target active architecture options so that it works with all your Pods. Some references - https://gist.github.com/funroll/7faf18b4972d72cd284e
